version: '3.9'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reussirsoncv_django
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    # Override command for local dev
    command: sh -c "python manage.py migrate && gunicorn reussirsoncv.wsgi:application --bind 0.0.0.0:8000"






