# Generated by Django 4.2.20 on 2025-07-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='resumeImages/'),
        ),
    ]
