# Generated by Django 4.2.20 on 2025-08-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_cv_section_order_alter_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='theme',
            field=models.JSONField(default=dict),
        ),
    ]
